# Generated by Django 4.0.5 on 2022-06-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='netflix_movies.category'),
            preserve_default=False,
        ),
    ]
