# Generated by Django 4.0.5 on 2022-06-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix_movies', '0004_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.TextField(default=None),
        ),
    ]
